<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-U3RVMDB3" failures="2" tests="5" name="Test0" time="47.03" errors="0" timestamp="2022-12-23T14:49:07 ECT">
  <testcase classname="com.examplet.testng.Login_Test1" name="login" time="4.299"/>
  <testcase classname="com.examplet.testng.Login_Test1" name="login" time="4.222">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at com.examplet.testng.Login_Test1.login(Login_Test1.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="com.examplet.testng.Login_Test1" name="login" time="4.221"/>
  <testcase classname="com.examplet.testng.Login_Test2" name="login" time="9.271"/>
  <testcase classname="com.examplet.testng.Login_Test2" name="login" time="4.199">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at com.examplet.testng.Login_Test2.login(Login_Test2.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test0 -->
